server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Google issuer (required)
          issuer-uri: https://accounts.google.com

app:
  security:
    google:
      # This MUST equal the Google OAuth Client ID you used as the audience
      # when you minted the ID token with gcloud (print-identity-token --audiences=...)
      client-id: "546784338173-keh6ir709uiip9dqkp79k4lnua4mr4k3.apps.googleusercontent.com"

      # Optional: allow-list for roles (if you use emailâ†’role mapping)
      super-admin-emails:
        - "vetsecure-local@vetsecure-prod.iam.gserviceaccount.com"
        - "sandacrudu72@gmail.com"